name: 'Get GitVersion'
description: 'Calculate the version of the current commit.'
outputs:
  ShortVersion:
    description: "major.minor.patch"
    value: ${{ steps.asmVer.outputs.ver }}
  LongVersion:
    description: "major.minor.patch-prerelease"
    value: ${{ steps.longVer.outputs.ver }}
  GitVersion:
    description: "major.minor.patch-prerelease+commithash.branchname"
    value: ${{ steps.gitVer.outputs.ver }}
  GitVersionPrerelease:
    description: "prerelease"
    value: ${{ steps.prereleaseVer.outputs.ver }}
runs:
  using: "composite"
  steps:
    - uses: opentap/setup-opentap@v1.0
      with:
        # this version introduced a change to gitversion behavior. Once the change is released, we should replace this with a release version, and make a new get-gitversion release
        version: 9.23.2-beta.16
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fix tags
      shell: bash
      if: startsWith(github.ref, 'refs/tags/v')
      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }} # Fixes an issue with actions/checkout@v2. See https://github.com/actions/checkout/issues/290
    - name: tap sdk gitversion --fields 3
      shell: bash
      id: asmVer
      run: echo "VER=`tap sdk gitversion --fields 3`" >> $GITHUB_OUTPUT
    - name: tap sdk gitversion --fields 4
      shell: bash
      id: longVer
      run: echo "VER=`tap sdk gitversion --fields 4`" >> $GITHUB_OUTPUT
    - name: tap sdk gitversion
      shell: bash
      id: gitVer
      run: echo "VER=`tap sdk gitversion`" >> $GITHUB_OUTPUT
    - name: Prerelease
      shell: bash
      id: prereleaseVer
      run: echo "VER=`tap sdk gitversion | sed -n 's/.*-\([^+]*\).*/\1/p'`" >> $GITHUB_OUTPUT
    - name: Print Version
      shell: bash
      run: echo `tap sdk gitversion`


