name: 'Get GitVersion'
description: 'Calculate the version of the current commit.'
outputs:
  ShortVersion:
    description: "a.b.c"
    value: ${{ steps.asmVer.outputs.ver }}
  LongVersion:
    description: "a.b.c-prerelease"
    value: ${{ steps.longVer.outputs.ver }}
  GitVersion:
    description: "a.b.c-prerelease+commithash.branchname"
    value: ${{ steps.gitVer.outputs.ver }}
runs:
  using: "composite"
  steps:
    - uses: opentap/setup-opentap@v1.0
      with:
        version: 9.16.4
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fix tags
      shell: bash
      if: startsWith(github.ref, 'refs/tags/v')
      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }} # Fixes an issue with actions/checkout@v2. See https://github.com/actions/checkout/issues/290
    - name: tap sdk gitversion --fields 3
      shell: bash
      id: asmVer
      run: echo ::set-output name=ver::`tap sdk gitversion --fields 3`
    - name: tap sdk gitversion --fields 4
      shell: bash
      id: longVer
      run: echo ::set-output name=ver::`tap sdk gitversion --fields 4`
    - name: tap sdk gitversion
      shell: bash
      id: gitVer
      run: echo ::set-output name=ver::$(tap sdk gitversion)  


