on: [push]

jobs:
  test-linux:
    runs-on: ubuntu-20.04
    name: Test Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0        
      - name: GitVersion
        id: v
        uses: ./ # This repo action
      - name: Test
        run: 
          echo ${{ v.outputs.ShortVersion }}
          echo ${{ v.outputs.LongVersion }}
          echo ${{ v.outputs.GitVersion }}

  test-win:
    runs-on: windows-2022
    name: Test Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0        
      - name: GitVersion
        id: v
        uses: ./ # This repo action
      - name: Test
        run: 
          echo ${{ v.outputs.ShortVersion }}
          echo ${{ v.outputs.LongVersion }}
          echo ${{ v.outputs.GitVersion }}